mappings:
  GET AIF:
    host: 10.185.36.195
    port: 8003
    dir: ace
    timeout: 500
  tab-auth-api:
    host: http://tab-auth-api.int.hotelbeds.com
    dir: tab-auth-api

cache:
  strategy: FileCache
  baseDir: /home/pablo/tmp

tcpSeparator: "-"

server:
  port: 3001