proxy:
  mappings:
    GET AIF:
      host: ace-hotel
      port: 8003
      dir: ace
      timeout: 500
      linesToRead: 0
      discovery: true
    tab-auth-api:
      host: http://tab-auth-api.int.hotelbeds.com
      dir: tab-auth-api

    consul:
      host: consul.test.service
      port: 8500
      dir: consul


  cache:
    strategy: FileCache
    baseDir: /home/pablo/tmp

  tcpSeparator: "-"

  port: 3001
